### ISSUE TITLE
Can't get it to work behind reverse proxy

### ISSUE THREAD

**Issue by jleechpe** [NicFragale/HA-NetFoundry#4]
Hi,

I'm trying to test this out and running into an issue getting it to work behind a Caddy reverse proxy.

I'd previously gotten it to work using a separate machine on my home network and tunneling over

Caddy->EdgeTunnel(cloud Linux)->OpenZiti->EdgeTunnel(Local Linux)->HomeAssistant(raspberry pi)

Caddyfile
```
hass.example.com {
  reverse_proxy hass.home.ziti:8123
}
```
Intercept for `hass.home.ziti:8123` with the host pointing to `192.168.x.x:8123`

but switching to using the plugin just ends up with a bad request even after updating the trusted proxies to include `100.64.0.0/16`

Caddyfile
```
hass.example.com {
  reverse_proxy hassio.home.ziti # tried hassio.home.ziti:8123 as well
}
```
Intercept for `hassio.home.ziti` on port 80 (tried 8123 as well) pointing to `localhost:8123`.  The cloud machine can `curl hassio.home.ziti` successfully.

**Comment by NicFragale** [comment]
Hi there!  Thanks for checking out the plugin.  I will respond in full early next week when I am back at my office.  (Or earlier if I gain access to my laptop in the mean time).

**Comment by NicFragale** [comment]
Hi @jleechpe - Apologies for the latency in getting back to you on this.  It popped up and reminded me when another issue arose that sounded similar.   A DNS issue crept into the build for the underlying CSDK Tunnel of ZITI EDGE TUNNEL.  A few updates later and it seems to have been resolved.  I am curious if you got things working on your own or if you are still stuck.  The latest version (1.5.2) should address a number of things that I think are related.
