### ISSUE TITLE
What does the openziti add-on do in home assistant?

### ISSUE THREAD

**Issue by qrkourier** [NicFragale/HA-NetFoundry#5]
https://github.com/NicFragale/HA-NetFoundry/tree/main/openziti#readme

What does it do, and how does it work?

**Comment by NicFragale** [comment]
This is a standalone ZITI EDGE TUNNEL running in a container under Home Assistant.  It allows ZET to run as a "host only" or "intercepting" model.  The easiest model to run is "host" where ZET simply terminates connections to its LAN or loopback.  In this model, an identity that intercepts can reach Home assistant without the need for a cloud to do so.

Example, Home Assistant for mobile (like iOS) can reach the Home Assistant server in LAN while roaming on cellular.  You would set an intercepting service that captures requests to ziti.myha.com:8123 (terminating at the ZET on Home Assistant using 127.0.0.1:8123) and assign this as a service policy that is associated to the mobile phone's identity.  With ZME on, and the Home Assistant app running and pointed at ziti.myha.com:8123, requests would route over ZITI and terminate to the Home Assistant server listening for access requests from the LAN OR localhost only.  You then have a private Home Assistant that is not exposed to the Internet directly or via a cloud bridge.


I'll add this to the README soon as well.

**Comment by NicFragale** [comment]
closed through update #7
